version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 2s
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: ghcr.io/jaws-tm/l-agence/backend:master
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      FRONTEND_URL: ${SITE_URL}
    volumes:
      - pictures:/app/public/uploads
      - sessions:/app/sessions

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    image: ghcr.io/jaws-tm/l-agence/frontend:master
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - ${PROXY_PORT}:80

volumes:
  database:
  pictures:
  sessions:
