# Build stage
FROM node:18-alpine AS builder
WORKDIR /app

COPY packages/backend/package.json packages/backend/yarn.lock ./
RUN yarn

COPY packages/backend .
RUN yarn build

# EXPOSE 8080

ENTRYPOINT ["node", "./dist/server.js"]