FROM node:18-alpine AS builder
WORKDIR /app

# Install app dependencies
COPY packages/frontend/package.json packages/frontend/yarn.lock ./
RUN yarn 

COPY packages/frontend .
RUN yarn build

# Stage 2
#######################################
FROM nginx:1.19.0 AS runner
WORKDIR /app

COPY --from=builder /app/dist .
COPY docker/proxy.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]